### ISSUE TITLE
ln: failed to create symbolic link '/nix/store/…-android-build-tools-r23.0.0/build-tools/23.0.0/lib64/libtinfo.so.5': No such file or directory

### ISSUE THREAD

**Issue by siers** [uniphil/nix-react-native-base#1]
Entering the nix-shell currently fails. (Disclaimer: I haven't used react native ever.)

    % nix-shell
    these derivations will be built:
      /nix/store/56w0z8ah1j3v82cj20lvzd2v85h7zpp0-run-android-usr-multi.drv
      /nix/store/9yiq8iss0s1jsyxv57gx06qx6lazmr5a-profile.drv
      /nix/store/kgm0ra3axvxvjrvr9qq6q2xzpj23qsrr-run-android-chrootenv-etc.drv
      /nix/store/wcsivw09bi6dhyiwj6y4d1al5r68h1rb-run-android-usr-target.drv
      /nix/store/7cdp0pv58ykqf5p7wrxvyxsbw141yiby-run-android-fhs.drv
      /nix/store/zd77krs4qqaj4px8y55cwb0gykgxgmmw-run-android-init.drv
      /nix/store/4r7kg4amdnh89b1abq0jljb120kzw26y-run-android.drv
      /nix/store/98pqmyy8d9309nyfjyd7qa39j9f9qik5-sources-23_r01.zip.drv
      /nix/store/9qv4p0izk0fa5hp6siqqdkz3wrjvbzcn-x86-23_r10.zip.drv
      /nix/store/c2262nghx481qfzn44xjjpsznrajjk2c-emulator-linux-4969155.zip.drv
      /nix/store/dadpa0y0mc9p46cac77p0c5vm3a2q1pn-source.drv
      /nix/store/ibl2q1d86lvb6rhl0xd822gb69jv4d0d-android-build-tools-r23.0.0.drv
      /nix/store/j6c5k9fhs10z5xrvk1dwj4sbh4i7yv52-sdk-tools-linux-4333796.zip.drv
      /nix/store/lcjha1h1k3b0v5kmy49zjq6mb5171wxz-android-support-repository-r47.drv
      /nix/store/s6hadk76l3qvla2g81i1va8b0kk1c988-android-source-23.drv
      /nix/store/xck5inql1g2bx36h58rrp0g3hcl81phg-sysimg-x86-23.drv
      /nix/store/l7y0w0khxal8q49cvljyqhl8r92vnd06-android-sdk-26.1.1.drv
      /nix/store/xknk4nlf7q8hgj2a249qc791c08zykad-unpatched-sdk.drv
    building '/nix/store/ibl2q1d86lvb6rhl0xd822gb69jv4d0d-android-build-tools-r23.0.0.drv'...
    building '/nix/store/lcjha1h1k3b0v5kmy49zjq6mb5171wxz-android-support-repository-r47.drv'...
    building '/nix/store/c2262nghx481qfzn44xjjpsznrajjk2c-emulator-linux-4969155.zip.drv'...
    building '/nix/store/j6c5k9fhs10z5xrvk1dwj4sbh4i7yv52-sdk-tools-linux-4333796.zip.drv'...
    Archive:  /nix/store/62863sqna7wq7yqfd06dj7hvxp7nfkyi-build-tools_r23-linux.zip
       creating: android-6.0/
     extracting: android-6.0/runtime.properties
    Archive:  /nix/store/qfcidsmnb65pnspc8yyff20axnvf8njy-android_m2repository_r47.zip
       creating: m2repository/
      inflating: m2repository/NOTICE.txt
       creating: m2repository/com/
    [… 4119 lines …]
      inflating: m2repository/com/android/support/leanback-v17/23.4.0/leanback-v17-23.4.0-javadoc.jar.sha1
    ln: failed to create symbolic link '/nix/store/5wshsrn994m0aqzlnrizcgcrzqxvga4j-android-build-tools-r23.0.0/build-tools/23.0.0/lib64/libtinfo.so.5': No such file or directory
      inflating: m2repository/com/android/support/leanback-v17/23.4.0/leanback-v17-23.4.0-sources.jar
    [… 19 lines …]
      inflating: m2repository/com/android/support/leanback-v17/25.1.0/leanback-v17-25.1.0-javadoc.jar.sha1
    builder for '/nix/store/ibl2q1d86lvb6rhl0xd822gb69jv4d0d-android-build-tools-r23.0.0.drv' failed with exit code 1
    cannot build derivation '/nix/store/l7y0w0khxal8q49cvljyqhl8r92vnd06-android-sdk-26.1.1.drv': 1 dependencies couldn't be built
    error: build of '/nix/store/4r7kg4amdnh89b1abq0jljb120kzw26y-run-android.drv', '/nix/store/l7y0w0khxal8q49cvljyqhl8r92vnd06-android-sdk-26.1.1.drv', '/nix/store/xknk4nlf7q8hgj2a249qc791c08zykad-unpatched-sdk.drv' failed

**Comment by siers** [comment]
This was tested on 18.09, but seems to be failing with a NIX_PATH set to 18.03 channel too.

**Comment by uniphil** [comment]
yikes

i haven't looked at this since 2017, so i'm not sure what part is at issue here. i'll take a pr if you figure it out though!

**Comment by siers** [comment]
Ok! :) It's still better to have an issue detailing that it no longer works to give heads up to the next people who found this through google search. (It's high up.)

**Comment by siers** [comment]
I later quickly realized that it's because simply `androidsdk` was failing to build. Sorry for the trouble, this builds fine now and most likely will work for me, now that I've finally starting to understand what this all android jazz does.
